# Generated by Django 3.2.5 on 2023-03-17 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Speciality', models.CharField(blank=True, choices=[('Cardiologist', 'Cardiologist'), ('Audiologists', 'Audiologists'), ('Cardiothoracic Surgeon', 'Cardiothoracic Surgeon'), ('Dentist', 'Dentist'), ('Endocrinologist', 'Endocrinologist'), ('ENT Specialists', 'ENT Specialists'), ('Gynecologists', 'Gynecologists'), ('Neurologists', 'Neurologists'), ('Oncologists', 'Oncologists'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Pediatrician', 'Pediatrician'), ('Psychiatrists', 'Psychiatrists'), ('Pulmonologists', 'Pulmonologists'), ('Radiologist', 'Radiologist'), ('Veterinarian', 'Veterinarian')], max_length=100, null=True)),
                ('Mobile_no', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='myimages')),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('status_by_hospital', models.BooleanField(default=False)),
                ('joining_data', models.DateField(auto_now_add=True)),
                ('Languages', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved_by_doctor', models.BooleanField(default=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Mobile_no', models.IntegerField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='myimages')),
                ('is_admited', models.BooleanField(default=False)),
                ('Staus_by_hospital', models.BooleanField(default=False)),
                ('status_by_doctor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_profile_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor_profile')),
                ('patient_profile_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient_profile')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDischargeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('admitDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('daySpent', models.PositiveIntegerField()),
                ('roomCharge', models.PositiveIntegerField()),
                ('medicineCost', models.PositiveIntegerField()),
                ('doctorFee', models.PositiveIntegerField()),
                ('OtherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('assignedDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor_profile')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient_profile')),
            ],
        ),
        migrations.AddField(
            model_name='patient_profile',
            name='patient_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('doctor_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient_profile')),
                ('patient_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor_profile')),
            ],
        ),
        migrations.AddField(
            model_name='doctor_profile',
            name='doctor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateTimeField()),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted_by_doctor', models.BooleanField(default=False)),
                ('is_rejected_by_doctor', models.BooleanField(default=False)),
                ('Doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_id', to='Doctor.doctor_profile')),
                ('Patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_id', to='Doctor.patient_profile')),
            ],
        ),
    ]
