# Generated by Django 3.2.5 on 2023-03-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='likes',
            field=models.ManyToManyField(to='Doctor.Patient_profile'),
        ),
    ]
