# Generated by Django 3.2.5 on 2023-03-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20230320_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientDischargeDetails',
            new_name='PatientAdmitted',
        ),
    ]
