# Generated by Django 3.2.5 on 2023-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_rename_patientdischargedetails_patientadmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientadmitted',
            name='symptoms',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
