# Generated by Django 3.2.5 on 2023-03-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_alter_patientadmitted_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientadmitted',
            name='OtherCharge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientadmitted',
            name='admitDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientadmitted',
            name='daySpent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientadmitted',
            name='doctorFee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientadmitted',
            name='medicineCost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientadmitted',
            name='releaseDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientadmitted',
            name='roomCharge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientadmitted',
            name='symptoms',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
