# Generated by Django 3.2.5 on 2023-03-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_auto_20230327_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientadmitted',
            name='admitDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientadmitted',
            name='releaseDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
