# Generated by Django 3.2.5 on 2023-03-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_auto_20230327_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientadmitted',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
