# Generated by Django 3.2.5 on 2023-03-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0009_alter_patientadmitted_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_profile',
            name='Staus_by_hospital',
        ),
        migrations.RemoveField(
            model_name='patient_profile',
            name='status_by_doctor',
        ),
        migrations.AddField(
            model_name='patientadmitted',
            name='Staus_by_hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientadmitted',
            name='status_by_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
