# Generated by Django 3.2.5 on 2023-03-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0010_auto_20230330_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientadmitted',
            name='symptoms',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
