# Generated by Django 3.2.5 on 2023-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0011_alter_patientadmitted_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmitted',
            name='is_discharged',
            field=models.BooleanField(default=True),
        ),
    ]
