# Generated by Django 3.2.5 on 2023-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0012_patientadmitted_is_discharged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientadmitted',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
    ]
