# Generated by Django 3.2.5 on 2023-04-06 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0013_alter_patientadmitted_is_discharged'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='auth_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
