# Generated by Django 4.2 on 2023-04-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0018_payment_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='patient_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patient_profile'),
        ),
    ]
