# Generated by Django 4.2 on 2023-04-17 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0021_alter_payment_patient_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='patient_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.patientadmitted'),
        ),
    ]
