# Generated by Django 4.2 on 2023-04-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0022_alter_payment_patient_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientadmitted',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
