# Generated by Django 4.2 on 2023-04-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0023_alter_patientadmitted_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientadmitted',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
