# Generated by Django 4.2 on 2023-04-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0024_alter_patientadmitted_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientadmitted',
            name='total',
        ),
    ]
