# Generated by Django 4.2 on 2023-04-17 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0026_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 17, 11, 9, 55, 744315, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
