# Generated by Django 4.2 on 2023-04-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0027_alter_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
