# Generated by Django 4.2 on 2023-04-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0029_payment_payment_date_alter_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
